travis:
  secure:
    BINSTAR_TOKEN: H4uF06IfOYmeNPDLoLIqIXDcLL24tIPR7tz5PU8YhV5E8SW9fe9XnunUzqcD5PyjmRlK8dgVM2UXfQ/suJpEbyRd49WbnfCJobVZEt6m1ZYOTuDR4yLCeddgQmI7H6U6XCXAjinIAF+AkZ98mZcknDv/3gd1LktzBl3ulyaWfm825loqK7/KDu1XSBJVboxLW6I9aoJvwt77rN3qspO0l04uj1fscvzHFjD/qVnfobWQYxZFgVzneMFZbYElZ8HKLSY/gG5hxunf806vC/UeiMRP7CIAIvGFO8oSH4gUcS1iBQBkwQtQYCb0J4db9DVem/pLoyEwNFw/TdUnWC3KXuFdVrwuwO9a0UniPAZD4H7Tz3lmkkvfzZB4iegnCgLMYB5us5z9iiw+Vmemm+lcHZFnjl2bYVJzYIUluyLY6JloeaBiRMJ29p4Aa6HuGi1xwFPxni1TkGCQDzfx76uzd+LcEe2gNbLBa47VZNPkUGvbnCTKUeXWd5MDPAUVaYN2Fzu0ytynKLW2Q83vo8AzPY8F1G0glDhzlgJNE1nM/VmPnsoT7SGgxEk3seQLuhGOMWmsF8wXv7FDcWk+jr0NkdshseVebfVRC5S5XOi5IwXerIMZFAVmvtPNqz2F0gukm7rCqCttxBDcas67IUilbqiqWXdtEN7x5VCv7mmc6cc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
