travis:
  secure:
    BINSTAR_TOKEN: JyIxM0jgSxa9hk+8O+7mwxYDo92zFGCg0X+OJwozwkXEXswcnYwgyj6dRX6XGDLxvyzAHeQMxjf9p6UpP6ns5qCHPAzSVz9PqRcdnD4g+y4t5aGmN4V1FE05pKijOFv+bI3chieeHSdJXUjVdY5YPgWxz+J+Tc8hvgO++DU3hjc7IYq7GIcVtfzvUtXabwvcCt9rxOxmvp/1YFHMTq9tqiEi7XaokdloxIiSitByUOw7OxggGwAwBf/EnCh9rXcuBcitZm5Zj40dGsZGCsKSOAwNEyOLzoz5B0qc35sW423KsvWmfr+UC5pMTrHHECKZR0JbmBMhY+r8X8WmB9ja5vaUWeqtjE3uY+c3oEZp2kxVPmNdu6B4c+uKcnPZIeCxW9tZILal/JlGObwAcG2SKhXvL1GXm4Yp1T7ab8RiYUFxZFoTWxouHrewUg8LbKHRE8rSeVFmD3VfO4BVBh7DGl6uPA0VoisDNdLG0OveimNhl0gx/gbohIWfmWD2OTKeQdES9HTSQo+yRuncY7MuKJnnWTIqGPwKsciSPKhz+RYLX+lZUP/P4Rt/HPt6ZsVg6aAox8oJqnYGWyoHKljk8Si2Kdk2iS6+OuqZ7n2IQDjvR/DYp/9YT/6vPJcCsYKvJ/NjSMSAhFlEP5UCM/0mnvxZMi4xDQLsPSzRHbYeYxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
